### ISSUE TITLE
Pasting external text - pnpm issue

### ISSUE THREAD

**Issue by liamb13** [jjjuulliiaann/sanity-nuxt-3-starter#2]
Just wondering if you're experiencing the pasting bug reported here: 
https://github.com/sanity-io/sanity/issues/3532#issuecomment-1319709025

**Comment by jjjuulliiaann** [comment]
Hi, yes I have the pasting bug in my starter as well. However in a client project with the same setup and studio version it works. (not sure what is different, but maybe it works because I used `sanity init` which uses yarn under the hood).

As a quick fix you can perform a `yarn install` inside the studio but I hope it does get fixed soon.

**Comment by jjjuulliiaann** [comment]
After updating the studio to 3.0.0 the problem seems to be fixed.
